### ISSUE TITLE
Problem with jetPair size

### ISSUE THREAD

**Issue by bortigno** [UFLX2MuMu/Ntupliser#18]
In the production there are a large amount of events with this message:
== CMSSW: Bizzare error: jet _pairInfos.size() = 15, nPairs = 28

Not sure why. Maybe @abrinke1 has seen this before?

**Comment by abrinke1** [comment]
Looks like it comes from this line:
https://github.com/UFLX2MuMu/Ntupliser/blob/master/DiMuons/src/JetPairHelper.cc#L65

Caused because of this cut-off, which was added to avoid events with many jets having massive vectors of jetPair info:
https://github.com/UFLX2MuMu/Ntupliser/blob/master/DiMuons/src/JetPairHelper.cc#L36

Guess this would mostly happen with events with many jets.  You could modify the printout so that it does not have an error if jet _pairInfos.size() == 15 and nPairs > 15.

**Comment by bortigno** [comment]
Done in eb3bdf8
